### ISSUE TITLE
NodeSet for O-PAS Companion Specification

### ISSUE THREAD

**Issue by ra-alam** [OPCFoundation/UA-Nodeset#104]
Hello, 

Is there a plan to add the NodeSet files for the Open Process Automation Specification (O-PAS) under Companion Spec?

**Comment by JimLuth** [comment]
No.  The O-PAS standard is owned and licensed by the Open Group.  The O-PAS nodeset files are published as a part of their specifications here: https://publications.opengroup.org/standards/opa
