### ISSUE TITLE
.NET stack support files for PA-DIM

### ISSUE THREAD

**Issue by jnsjll** [OPCFoundation/UA-Nodeset#106]
Hi there,

do you know if there are existing efforts to provide the .NET stack support / ModelCompiler xml files for the PA-DIM specification? I would be very interested in it.

**Comment by opcfoundation-org** [comment]
The PADIM NodeSet can be provided as an input to the ModelCompiler:

`Opc.Ua.ModelCompiler compile-nodesets -input %NODESETS% -o2 .\Generated -uri http://opcfoundation.org/UA/PADIM/ -uri http://opcfoundation.org/UA/DI/ -prefix UAModel.PADIM`

Where %NODESETS% is the path to a local clone of https://github.com/OPCFoundation/UA-Nodeset

**Comment by jnsjll** [comment]
Thank you, much appreciated.
