### ISSUE TITLE
Updating Model-Version-Annotation in latest UANodeSet.xsd

### ISSUE THREAD

**Issue by jthielemann** [OPCFoundation/UA-Nodeset#107]
Hello everyone,

thanks for releasing the version 1.05.04 of the the core schema files. I noticed that a small change was made in the UANodeSet.xsd:
[added line in 1.05.04 commit](https://github.com/OPCFoundation/UA-Nodeset/blame/822f433561dc1ddbb5a8ee5bf35e5185c697057d/Schema/UANodeSet.xsd#L326
)
I'm happy to see that a model-information annotation was added in the previous release 1.05.02. But shouldn't the attribute `Version="1.05.02"` have been updated to 1.05.04 as well?:
[model information annotation in 1.05.02 commit](https://github.com/OPCFoundation/UA-Nodeset/blame/f11293ad04379bd6918dbe55fea669933948fcef/Schema/UANodeSet.xsd#L39
)

Thanks in advance!

**Comment by opcfoundation-org** [comment]
Good catch. Fixed.
