### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by mpostol** [OPCFoundation/UA-Nodeset#11]
- Add License.md file - the project doesn't have any license information. 
- Some files published in this repository says:  `OPC Foundation MIT License 1.00`, e.g. `..../Schema/Opc.Ua.Classes.cs` so the repository as one whole should say the same. 
- Mentioned above class (autogenerated I guess) refers to the definitions in a stuff that is not part of the repository, so it must be clearly stated where the files can be used - requirements about the context where they are applicable.
- The context where the files are applicable should have a consistent license, i.e it doesn't make sense to publish stuff under the MIT license, which is applicable only under the GPL license.  To be precise it is possible because GPL is more restrictive but useless. 

Anway, the license and applicability context should be clearly described - I mean licenses dependency chain and code dependency chain should be clear and consistent.

For example the code dependency chain inluse the following identyfiers (to name only a few):

- `BaseObjectState`
- `NodeState`
- `NodeId`
- `NamespaceTable`
- `GetDefaultTypeDefinitionId`
- `PropertyState`
- `TimeZoneDataType`

**Comment by opcfoundation-org** [comment]
Autogenerated code is MIT. If you need more than the autogenerated code then the more restrictive license applied.
