### ISSUE TITLE
QualifiedName in Opc.Ua.Types - NamespaceIndex has wrong type

### ISSUE THREAD

**Issue by erossignon** [OPCFoundation/UA-Nodeset#13]
https://github.com/OPCFoundation/UA-Nodeset/blob/676f54dc90f824224710493b80942ab494bc383e/Schema/Opc.Ua.Types.bsd#L137-L142

![image](https://user-images.githubusercontent.com/680220/43358814-f3b43482-9297-11e8-9cfc-a210c5d74a08.png)

Furthermore CharArray, could be replaced  by String. 

We would expect 
````
 <opc:Field Name="NamespaceIndex" TypeName="opc:UInt16" /> 
 <opc:Field Name="Name" TypeName="opc:String" /> 
````

**Comment by opcfoundation-org** [comment]
Fixed. Next checkin will have it.
