### ISSUE TITLE
Wrong DataType of FieldMetaData.FieldFlags in Opc.Ua.Core

### ISSUE THREAD

**Issue by skrausser** [OPCFoundation/UA-Nodeset#15]
Attribute „FieldFlags“ in class Opc.Ua.FieldMetaData is implemented as enumeration DataSetFieldFlags. WriteEnumerated and ReadEnumerated are used for this attribute in Encode and Decode implementation of Opc.Ua.FieldMetaData. Enumeration data types are encoded/decoded as Int32, however DataSetFieldFlags type should be UInt16 (OPC UA Specification, Part 14, Release 1.04, 6.2.2.1.4). WriteEnumerated/ReadEnumerated calls should be replaced with WriteUInt16/ReadUInt16, so binary data size for “FieldFlags” becomes 2 Bytes instead of 4 Bytes.
File: \Stack\Opc.Ua.Core\Stack\Generated\Opc.Ua.DataTypes.cs
Methods: Encode / Decode

**Comment by opcfoundation-org** [comment]
Fixed in latest v1.04.
