### ISSUE TITLE
Opc.Ua.Di.Classes.cs does not compile

### ISSUE THREAD

**Issue by nooelan** [OPCFoundation/UA-Nodeset#19]
The commit 6f8c38d6773fada59f2fb2b26ff70e54390b1d2c (Update DI to 1.02 Release Candidate) causes the generated Opc.Ua.Di.Classes.cs file to fail during build with the following errors:

Severity | Code | Description | File | Line
---------|------|-------------|------|-----
Error| CS0100 | The parameter name 'context' is a duplicate | Opc.Ua.Di.Classes.cs | 5915
Error| CS0841 | Cannot use local variable 'context' before it is declared | Opc.Ua.Di.Classes.cs | 5878
Error| CS0136 | A local or parameter named 'context' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter | Opc.Ua.Di.Classes.cs | 5883
Error| CS1503 | Argument 1: cannot convert from 'string' to 'Opc.Ua.ISystemContext' | Opc.Ua.Di.Classes.cs | 5890

The reason for these build errors are fairly obvious, but in short:

The `Call` funtion in line 5870 has a parameter `ISystemContext context`.
In line 5883 a variable is declared with the same name:

```C#
protected override ServiceResult Call(
   ISystemContext context,
   NodeId objectId,
   IList<object> inputArguments,
   IList<object> outputArguments)
{
   ...
   string context = (string)inputArguments[0];
   ...
}
```
Furthermore, the `InitLockMethodStateMethodCallHandler` function in line 5911 has two parameters named `context`:

```C#
    public delegate ServiceResult InitLockMethodStateMethodCallHandler(
        ISystemContext context,
        MethodState method,
        NodeId objectId,
        string context,
        ref int initLockStatus);
```

**Comment by opcfoundation-org** [comment]
Added mantis issue: https://apps.opcfoundation.org/mantis/view.php?id=4714

Latest code on master branch should fix.
