### ISSUE TITLE
OpcUaDi: Missing property Locked in LockingServicesType

### ISSUE THREAD

**Issue by mwimwi** [OPCFoundation/UA-Nodeset#24]
Is it intended that the property Locked is now missing in LockingServicesType definition (Namespace OpcUaDi)?

**Comment by opcfoundation-org** [comment]
Is this in the master branch or 1.04?

**Comment by mwimwi** [comment]
Only in the master branch.

**Comment by opcfoundation-org** [comment]
Master branch has changes for DI 1.02 . The spec itself is only available to WG members.
