### ISSUE TITLE
Circular reference in Opc.ISA95.NodeSet2.xml

### ISSUE THREAD

**Issue by indupriyac** [OPCFoundation/UA-Nodeset#28]
UAVariableType with NodeId="ns=1;i=5186" and BrowseName="1:MaterialLotPropertyType" has a child variable with NodeId="ns=1;i=5193" BrowseName="1:&lt;TestResult&gt;" whose type is again Node id "ns=1;i=5186". 
This creates a circular reference while parsing the variable type.

Please find the variable type definition for your reference.

<UAVariableType NodeId="ns=1;i=5186" BrowseName="1:MaterialLotPropertyType" DataType="Structure">
    <DisplayName>MaterialLotPropertyType</DisplayName>
    <Description />
    <References>
      <Reference ReferenceType="ns=1;i=4915">ns=1;i=5193</Reference>
      <Reference ReferenceType="ns=1;i=2009">ns=1;i=5200</Reference>
      <Reference ReferenceType="ns=1;i=4924">ns=1;i=5207</Reference>
      <Reference ReferenceType="HasSubtype" IsForward="false">ns=1;i=5165</Reference>
    </References>
  </UAVariableType>
  
  <UAVariable NodeId="ns=1;i=5193" BrowseName="1:&lt;TestResult&gt;" ParentNodeId="ns=1;i=5186" DataType="Structure">
    <DisplayName>&lt;TestResult&gt;</DisplayName>
    <References>
      <Reference ReferenceType="ns=1;i=4713">ns=1;i=5194</Reference>
      <Reference ReferenceType="ns=1;i=4713">ns=1;i=5195</Reference>
      <Reference ReferenceType="ns=1;i=4713">ns=1;i=5196</Reference>
      <Reference ReferenceType="ns=1;i=4713">ns=1;i=5197</Reference>
      <Reference ReferenceType="ns=1;i=4713">ns=1;i=5198</Reference>
      <Reference ReferenceType="ns=1;i=4713">ns=1;i=5199</Reference>
      <Reference ReferenceType="HasTypeDefinition">ns=1;i=5186</Reference>
      <Reference ReferenceType="HasModellingRule">i=11508</Reference>
      <Reference ReferenceType="ns=1;i=4915" IsForward="false">ns=1;i=5186</Reference>
    </References>
  </UAVariable>

**Comment by randy-armstrong** [comment]
That is intentional. It is allowed when the ModellingRule is MandatoryPlaceholder or OptionalPlaceholder.
