### ISSUE TITLE
Why are ArrayDimensions = 0 in the NodeSet files?

### ISSUE THREAD

**Issue by mlang-de** [OPCFoundation/UA-Nodeset#29]
In most cases the ArrayDimension is know for instance for InputArguments. Is there a reason why the ArrayDimensions is 0 all time?
Checked NodeSet file are BaseNodeSet and DI.

**Comment by randy-armstrong** [comment]
ArrayDimensions="0" means the 1 dimensional array can have any length.
It is only valid for ValueRank=1.
If it is specified for ValueRank != 1 then it is an error that needs fixing.

**Comment by mlang-de** [comment]
Here is my exmaple:
![image](https://user-images.githubusercontent.com/20433237/61889787-5c9d7b80-af06-11e9-8cd8-08bf176da33f.png)
Why is here ArrayDimension="0" used and not "2"?
Imho both are permitted.

**Comment by randy-armstrong** [comment]
ValueRank="1" in your example. The NodeSet appears to be correct.

**Comment by mlang-de** [comment]
The length of the ExtensionObject array is known, so why is this not indicated by the ArrayDimension with "2"? Regardless that "0" is also valid.

**Comment by opcfoundation-org** [comment]
The ArrayDimensions specifies a constraint on the Value of the Node. It does NOT indicate the length of the current value.

**Comment by mlang-de** [comment]
This is true, but in the example above it could be constrained, because the length is fixed by the specification.

**Comment by opcfoundation-org** [comment]
That is true.

**Comment by opcfoundation-org** [comment]
This is fixed in the version in OPCFMembers repo.
Will be published in the public repo in the next release.
