### ISSUE TITLE
IO-Link: IODDManagement NodeId changed

### ISSUE THREAD

**Issue by mlang-de** [OPCFoundation/UA-Nodeset#36]
Is it intended to change several NodeIds for the IODDManagement Nodes below the "Object"-Node?
Defined was the numerical NodeId 5022, 5024, 7002 and so on.
The current version in the master has changed these NodeIds starting from 10000.

**Comment by opcfoundation-org** [comment]
NodeIds should not change. Will investigate.

**Comment by mlang-de** [comment]
There was no changes in the nodeset file! This was my fault.
But the Companion Spec. defines a StaticNumericNodeId range vom 1-9999 the used NodeIds above 10000 are wrong.
Whether this will be change will be discussed in the OPC UA for IO-Link WG.
