### ISSUE TITLE
Missing ...Model.xml in TMC folder

### ISSUE THREAD

**Issue by gianlucabertuzzi** [OPCFoundation/UA-Nodeset#4]
In order to use ModelCompiler to auto-generate code, is it possible to add the "...Model.xml" (defined by “ModelDesign.xsd”)?
In other "Companion-Folder" (see PlcOpen for instance) the file is present (OpcUaPLCopenModel.xml for instance).

**Comment by opcfoundation-org** [comment]
The decision to provide the ModelDesign files to the OPC-F is up to the Companion WG. In some cases, the Companion WG uses different tools to create their NodeSet so there is no ModelDesign file available.
