### ISSUE TITLE
Wrong argument name "Context" for the method InitLockMethodType

### ISSUE THREAD

**Issue by ThomasRothfuss** [OPCFoundation/UA-Nodeset#41]
File: https://github.com/OPCFoundation/UA-Nodeset/blob/master/DI/OpcUaDiModel.xml 
Method: InitLockMethodType
ArgumentName: Context

The model compiler generates following C# method:

`    public delegate ServiceResult InitLockMethodStateMethodCallHandler(
        ISystemContext context,
        MethodState method,
        NodeId objectId,
        string context,
        ref int initLockStatus);`

The parameter name 'context' is a duplicate.

**Comment by randy-armstrong** [comment]
The latest version of the ModelCompiler fixes this issue.
