### ISSUE TITLE
Opc.Ua.NodeSet2.Services.xml InstanceNode and TypeNode "DataTypes" missing Purpose="CodeGenerator"

### ISSUE THREAD

**Issue by bjakke** [OPCFoundation/UA-Nodeset#48]
Hi,

The following types are not in the specification and are related to other similar Purpose="CodeGenerator" UADataType definitions, so I'm assuming these are just missing the definition in the XML.
```

  <UADataType NodeId="i=11879" BrowseName="InstanceNode">
    <DisplayName>InstanceNode</DisplayName>
    <References>
      <Reference ReferenceType="HasSubtype" IsForward="false">i=258</Reference>
    </References>
  </UADataType>
```
  
  
```
  <UADataType NodeId="i=11880" BrowseName="TypeNode">
    <DisplayName>TypeNode</DisplayName>
    <References>
      <Reference ReferenceType="HasSubtype" IsForward="false">i=258</Reference>
    </References>
  </UADataType>
```
This error is in both 1.04 and master branches.

(Basically I just need the Purpose="ServicesOnly" types, the "CodeGenerator" ones I'm excluding as they would make confusing API in my case.)

**Comment by opcfoundation-org** [comment]
Should be fixed now.
