### ISSUE TITLE
Missing MachineVision XML file conformant with ModelDesign.xsd

### ISSUE THREAD

**Issue by eoursel** [OPCFoundation/UA-Nodeset#53]
Hi guys, 

In MachineVisionn, the description of the model does not contain the XML representation compatible with ModelDesign.xsd which is mandatory for using the ModelCompiler. 

Or perhaps someone has already a tool to convert NodeSet2 to ModelDesign format? 

Regards

**Comment by opcfoundation-org** [comment]
Companion specifications are only required to provide a file compliant with UANodeSet.xsd. If the ModelDesign.xsd compliant inputs exist they will be added to the ModelCompiler project. 

If it does not exist then someone who wants the ModelDesign.xsd compliant input needs to create it themselves.

Adding support for  UANodeSet.xsd =>  ModelDesign.xsd conversion is an open feature request. We are waiting for someone that wants it enough to do the work and contribute it back to the shared codebase.
