### ISSUE TITLE
Incompatible XML and CSV for AutoID since Errata-1.04.5

### ISSUE THREAD

**Issue by andreasebner** [OPCFoundation/UA-Nodeset#58]
The uploaded AutoID NodeSet2.xml is based on an new 1.01 release whereas the NodeSet2.csv is still based on AutoID 1.0. Since there where new types added in 1.0.1 the csv file must also be updated.

**Comment by opcfoundation-org** [comment]
Issues with NodeSets need to be submitted as mantis issues:
https://apps.opcfoundation.org/mantis/set_project.php?project_id=94&amp;make_default=no
