### ISSUE TITLE
Connection Error with Reference Client 

### ISSUE THREAD

**Issue by GeorgMueller24** [OPCFoundation/UA-Nodeset#67]
Hi nauful,

Thank's for your great work! I just try out your library.

I try out the latest Reference Client (OPCFoundation/UA-.NETStandard ) to connect with your TestServer (NET Core).
But there is an NullReferenceException in the Reference client (trying read the IsAbstract attribute for Node Id 29).

**Comment by opcfoundation-org** [comment]
This is not the right place to report this kind of error. Try the OPCFoundation/UA-.NETStandand repo.
