### ISSUE TITLE
AnalogItemType has EURange but missing in Opc.Ua.Scales.NodeSet2.xml (GiveAway)

### ISSUE THREAD

**Issue by neeral85** [OPCFoundation/UA-Nodeset#68]
https://github.com/OPCFoundation/UA-Nodeset/blob/v1.04/Scales/Opc.Ua.Scales.NodeSet2.xml

on all GiveAway nodes mandatory EURange is missing. Example:

`<UAVariable NodeId="ns=1;i=511" BrowseName="1:GiveAway" ParentNodeId="ns=1;i=48" DataType="Number">
    <DisplayName>GiveAway</DisplayName>
    <Description>Defines the totalized value of volume above TargetWeight.</Description>
    <References>
      <Reference ReferenceType="HasTypeDefinition">i=2368</Reference>
      <Reference ReferenceType="HasComponent" IsForward="false">ns=1;i=48</Reference>
      <Reference ReferenceType="HasModellingRule">i=80</Reference>
    </References>
  </UAVariable>`

Missing:
`<Reference ReferenceType="HasProperty">ns=1;i=xxxx</Reference>`

`<UAVariable DataType="Range" ParentNodeId="ns=1;i=511" NodeId="ns=1;i=xxxx" BrowseName="EURange" AccessLevel="3">
        <DisplayName>EURange</DisplayName>
        <Description Locale="en"> Maximum range of values for GiveAway</Description>
        <References>
            <Reference ReferenceType="HasProperty" IsForward="false">ns=1;i=511</Reference>
            <Reference ReferenceType="HasTypeDefinition">i=68</Reference>
            <Reference ReferenceType="HasModellingRule">i=78</Reference>
        </References>
    </UAVariable>`

see here: 
https://reference.opcfoundation.org/v104/Scales/v100/docs/8.19.1/ 
https://reference.opcfoundation.org/v104/Core/docs/Part8/5.3.2/#5.3.2.3

**Comment by GoetzGoerisch** [comment]
Issue tracking is handled with [Mantis](https://apps.opcfoundation.org/mantis/login_page.php).

Please file an issue there.
