### ISSUE TITLE
Wrong argument name "Context" for the method InitLockMethodType - Still happening with ModelCompiler - master  c75b5bfe 

### ISSUE THREAD

**Issue by awol-o** [OPCFoundation/UA-Nodeset#73]
This issue (https://github.com/OPCFoundation/UA-Nodeset/issues/41) still happening when cloning latest ModelCompiler - master branch c75b5bfe and submodule Stack d7baeb9 and then compiling and the issue is still present in here 
https://github.com/OPCFoundation/UA-Nodeset/blob/40221c04f23576d612ad54aeb69ebb44ac7b442b/DI/Opc.Ua.Di.Classes.cs#L6033-L6038

**Comment by opcfoundation-org** [comment]
OK, this has been fixed in the OPCFMembers repo. It will published to public repo soon.
