### ISSUE TITLE
No ...PredefinedNodes.uanodes file for some nodesets

### ISSUE THREAD

**Issue by ebrithiljonas** [OPCFoundation/UA-Nodeset#74]
Is there a reason that there aren't PredefinedNodes.uanodes files for all the different nodesets? Specifically for the "IA", "Machinery" and "MachineTool" Folder. Also there are no xml files so I could compile these files myself with the ModelCompiler.

**Comment by opcfoundation-org** [comment]
The ModelCompiler input format is not a normative schema so Specification writers are only required to provide a NodeSet. 

We have asked for volunteers to develop a NodeSet to ModelCompiler schema convertor, however, so far there are no takers.
