### ISSUE TITLE
Outdated version of conan package "ua-nodeset/padim-1.02-2021-07-21"

### ISSUE THREAD

**Issue by hmi** [OPCFoundation/UA-Nodeset#91]
Hello, 
the available version of the ua-nodset conan package dont contains the Woodworking nodeset.
https://conan.io/center/ua-nodeset
Is it possible to provide a conan package which contains the current available nodesets.

Thank you.

**Comment by opcfoundation-org** [comment]
The conan upload link you provided was not provided by the OPC Foundation and there is no plan to support distribution of nodesets using that framework in the future. You need to contact who ever posted it there in the first place.

**Comment by hmi** [comment]
Thank you for the information and the quick reply
